@extends('layouts.admin')
@php($editing=$product->exists)
@section('title',$editing?'Edit '.$product->name:'Tambah Produk') @section('page-title',$editing?'Edit Produk':'Tambah Produk') @section('eyebrow',$editing?'ATUR PRODUK':'PRODUK BARU')
@section('content')
<form method="post" action="{{ $editing?route('admin.products.update',$product):route('admin.products.store') }}" enctype="multipart/form-data" class="section-card form-card">@csrf @if($editing)@method('PUT')@endif
<div class="section-head compact"><div><span class="kicker">INFORMASI DASAR</span><h2>{{ $editing?'Detail produk':'Buat produk baru' }}</h2></div></div>
<div class="form-grid two">
<label class="field"><span>Nama produk *</span><input name="name" value="{{ old('name',$product->name) }}" required placeholder="Contoh: Canva Premium"></label>
<label class="field"><span>Badge <small>(opsional)</small></span><input name="badge" value="{{ old('badge',$product->badge) }}" placeholder="Best Seller / Promo / New"></label>
<label class="field span-2"><span>Deskripsi</span><textarea name="description" rows="3" placeholder="Info singkat yang membantu customer memilih.">{{ old('description',$product->description) }}</textarea></label>
<label class="field span-2"><span>Keyword pencarian</span><input name="keywords" value="{{ old('keywords',$product->keywords) }}" placeholder="canva, desain, member, designer"><small>Pisahkan dengan koma. Dipakai agar search lebih mudah menemukan produk.</small></label>
</div>
<div class="form-block"><span class="field-title">Kategori *</span><div class="check-grid">@forelse($categories as $category)<label class="check-card"><input type="checkbox" name="categories[]" value="{{ $category->id }}" @checked(in_array($category->id,old('categories',$product->categories?->pluck('id')->all()??[])))><span>{{ $category->name }}</span></label>@empty<p class="helper">Belum ada kategori. Buat kategori terlebih dahulu.</p>@endforelse</div></div>
<div class="form-grid two">
<div class="form-block"><span class="field-title">Aturan jumlah pembelian</span><div class="radio-stack"><label><input type="radio" name="quantity_mode" value="multiple" @checked(old('quantity_mode',$product->quantity_mode ?: 'multiple')==='multiple')><span><b>Bisa membeli beberapa</b><small>Default. Customer bisa ubah quantity.</small></span></label><label><input type="radio" name="quantity_mode" value="single" @checked(old('quantity_mode',$product->quantity_mode)==='single')><span><b>Hanya 1 per pesanan</b><small>Quantity otomatis dikunci 1.</small></span></label></div></div>
<div class="form-block"><span class="field-title">Tampilan produk</span><label class="toggle-line"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$product->exists?$product->is_active:true))><span class="toggle"></span><span><b>Aktif di pricelist</b><small>Matikan untuk menyembunyikan tanpa menghapus.</small></span></label></div>
</div>
<div class="form-block"><label class="field"><span>Gambar aplikasi</span><input type="file" name="image" accept="image/png,image/jpeg,image/webp" data-image-input data-preview-target="#productImagePreview"><small>JPG/PNG/WebP, maks. 3 MB. Foto persegi atau mendekati persegi paling rapi.</small></label><div class="image-tools"><div class="image-preview" id="productImagePreview" data-image-preview>@if($product->image_path)<img src="/storage/{{ $product->image_path }}" alt="Preview">@else<span>Preview gambar</span>@endif</div>@if($editing && $product->image_path)<label class="remove-media"><input type="checkbox" name="remove_image" value="1"><span>Hapus gambar saat disimpan</span></label>@endif</div></div>
<div class="form-actions"><a class="button ghost" href="{{ route('admin.products.index') }}">Batal</a><button class="button primary" type="submit">{{ $editing?'Simpan Informasi':'Buat & Lanjut Varian' }}</button></div>
</form>

@if($editing)
<div class="section-card"><div class="section-head"><div><span class="kicker">OPSI PRODUK</span><h2>Pilihan seperti marketplace</h2><p>Contoh opsi: Tipe, Durasi, Device. Setiap opsi punya beberapa pilihan.</p></div></div>
<div class="option-admin-grid">
@foreach($product->options as $option)
<section class="option-admin-card"><div class="option-admin-head"><div><small>OPSI</small><h3>{{ $option->name }}</h3></div><form method="post" action="{{ route('admin.products.options.destroy',[$product,$option]) }}" data-confirm="Hapus opsi {{ $option->name }}?">@csrf @method('DELETE')<button class="icon-danger" type="submit">×</button></form></div>
<form method="post" action="{{ route('admin.products.options.update',[$product,$option]) }}" class="inline-add option-rename">@csrf @method('PUT')<input name="name" value="{{ $option->name }}" required><button class="button ghost small" type="submit">Ubah nama</button></form>
<div class="value-edit-list">@forelse($option->values as $value)<div class="value-edit-row"><form method="post" action="{{ route('admin.products.options.values.update',[$product,$option,$value]) }}" class="inline-add">@csrf @method('PUT')<input name="value" value="{{ $value->value }}" required><button class="button ghost small" type="submit">Simpan</button></form><form method="post" action="{{ route('admin.products.options.values.destroy',[$product,$option,$value]) }}" data-confirm="Hapus pilihan {{ $value->value }}?">@csrf @method('DELETE')<button class="icon-danger" type="submit">×</button></form></div>@empty<small class="helper">Belum ada pilihan.</small>@endforelse</div>
<form method="post" action="{{ route('admin.products.options.values.store',[$product,$option]) }}" class="inline-add value-add">@csrf<input name="value" required placeholder="Tambah pilihan, mis. 1 Bulan"><button class="button soft small" type="submit">Tambah</button></form></section>
@endforeach
<section class="option-admin-card add-option"><form method="post" action="{{ route('admin.products.options.store',$product) }}">@csrf<label class="field"><span>Tambah nama opsi</span><input name="name" required placeholder="Contoh: Durasi"></label><button class="button soft full" type="submit">+ Tambah Opsi</button></form></section>
</div></div>

<div class="section-card"><div class="section-head"><div><span class="kicker">VARIAN & HARGA</span><h2>Kombinasi yang dijual</h2><p>Hanya kombinasi yang dibuat di sini yang dapat dipilih customer.</p></div><a class="button ghost small" href="{{ route('admin.products.quick-edit') }}">Quick Edit Harga</a></div>
<div class="variant-list">@forelse($product->variants as $variant)<article class="variant-row"><div><div class="variant-labels">@forelse($variant->values as $value)<span><small>{{ $value->option->name }}</small>{{ $value->value }}</span>@empty<span><small>PAKET</small>Utama</span>@endforelse</div><div class="variant-price"><b>Rp{{ number_format($variant->promo_price ?: $variant->regular_price,0,',','.') }}</b>@if($variant->promo_price)<del>Rp{{ number_format($variant->regular_price,0,',','.') }}</del>@endif<span class="status {{ $variant->availability_status==='ready'?'ready':'sold' }}">{{ $variant->availability_status==='ready'?'Ready':'Sold Out' }}</span></div></div><form method="post" action="{{ route('admin.products.variants.destroy',[$product,$variant]) }}" data-confirm="Hapus kombinasi varian ini?">@csrf @method('DELETE')<button class="button danger small" type="submit">Hapus</button></form></article>@empty<div class="admin-empty slim">Belum ada kombinasi harga.</div>@endforelse</div>
<form method="post" action="{{ route('admin.products.variants.store',$product) }}" class="variant-create">@csrf
<div class="form-grid two">@foreach($product->options as $option)<label class="field"><span>{{ $option->name }} *</span><select name="values[]" required><option value="">Pilih {{ $option->name }}</option>@foreach($option->values as $value)<option value="{{ $value->id }}">{{ $value->value }}</option>@endforeach</select></label>@endforeach
<label class="field"><span>Harga normal *</span><input type="number" name="regular_price" min="0" required inputmode="numeric" placeholder="25000"></label><label class="field"><span>Harga promo</span><input type="number" name="promo_price" min="0" inputmode="numeric" placeholder="Opsional"></label><label class="field"><span>Status *</span><select name="availability_status"><option value="ready">Ready</option><option value="sold_out">Sold Out</option></select></label></div>
<button class="button primary" type="submit">+ Tambah Kombinasi</button></form>
</div>
<div class="danger-zone"><div><b>Hapus produk</b><p>Produk dan semua varian akan dihapus permanen.</p></div><form method="post" action="{{ route('admin.products.destroy',$product) }}" data-confirm="Hapus {{ $product->name }} beserta semua varian?">@csrf @method('DELETE')<button class="button danger" type="submit">Hapus Produk</button></form></div>
@endif
@endsection
